### ISSUE TITLE
URL Structure 

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#104]
AC:

- [x] Add new url structure.
########################################### What we do  ############################################

DEVOPS

DevOps as a Service - https://dev.dedicatted.com/what-we-do/devops/devOps-as-a-service

CLOUD MIGRATION

Readiness Assessment - https://dev.dedicatted.com/what-we-do/cloud-migration/readiness-assessment
Cloud Architecture and migration - https://dev.dedicatted.com/what-we-do/cloud-migration/cloud-architecture-and-migration
Hybrid Cloud - https://dev.dedicatted.com/what-we-do/cloud-migration/hybrid-cloud

CLOUD SERVICES

Cloud Native Development - https://dev.dedicatted.com/what-we-do/cloud-services/cloud-native-development
Cloud Optimisation - https://dev.dedicatted.com/what-we-do/cloud-services/cloud-optimisation
App Modernisation - https://dev.dedicatted.com/what-we-do/cloud-services/app-modernisation

CONSULTING

DevOps Consultiing - https://dev.dedicatted.com/what-we-do/consultiing/devops-consultiing
Cloud Infrastructure and design - https://dev.dedicatted.com/what-we-do/consultiing/devops-consultiing/#cloud-infrastructure-and-design
Cloud migration consulting - https://dev.dedicatted.com/what-we-do/consultiing/devops-consultiing/#cloud-migration-consulting
Security Audit - https://dev.dedicatted.com/what-we-do/consultiing/devops-consultiing/#security-audit
Kubernetes and Docker consulting - https://dev.dedicatted.com/what-we-do/consultiing/devops-consultiing/#kubernetes-and-Docker-consulting

########################################### Solutions  ##########################################

CLOUDS

Amazon AWS - https://dev.dedicatted.com/solutions/clouds/amazon-aws
Google Cloud - https://dev.dedicatted.com/solutions/clouds/google-cloud
Microsoft Azure - https://dev.dedicatted.com/solutions/clouds/microsoft-azure

KEY TECHNOLOGIES

Infrastructure as a Code - https://dev.dedicatted.com/solutions/key-technologies/infrastructure-as-a-code
Continuous integration and delivery - https://dev.dedicatted.com/solutions/key-technologies/continuous-integration-and-delivery
Kubernetes - https://dev.dedicatted.com/solutions/key-technologies/kubernetes

PLATFORMS & SOLUTIONS

Serverless automated platform - https://dev.dedicatted.com/solutions/platforms-and-solutions/serverless-automated-platform
GitOps with continuous delivery - https://dev.dedicatted.com/solutions/platforms-and-solutions/gitops-with-continuous-delivery
BigData platform - https://dev.dedicatted.com/solutions/platforms-and-solutions/bigdata-platform

############################################## Company  ##########################################

ABOUT US

Our customers - https://dev.dedicatted.com/company/about-us/our-customers
Contacts - https://dev.dedicatted.com/company/about-us/contacts
Blog - https://dev.dedicatted.com/company/about-us/blog
Job openings - https://dev.dedicatted.com/company/about-us/job-openings

**Comment by bcmp4p1** [comment]
App modernisation is not ready page

**Comment by Natali-Oliinyk-qa** [comment]
DEVOPS

DevOps as a Service - https://dev.dedicatted.com/what-we-do/devops/devOps-as-a-service

this link doesn't work (404 error) ,correct link 
https://dev.dedicatted.com/what-we-do/devops/devops-as-a-service/
