### ISSUE TITLE
Header release 

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#105]
AC:
- [x] Hide pages from the header :
                      Cloud Architecture and migration
                      Infrastructure as a Code
                      Continuous integration and delivery
                      Serverless automated platform
                      BigData platform
                      Our customers
                      Job openings
- [ ] Link blog to https://blog.dedicatted.com/
- [x] Hide contact form:
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/f1e062f8-f345-419e-911b-1ffd752dcf5a)
- [x] Hide **Success stories**,
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/561dc7ba-1635-4dba-a6cf-55ec7cd3794d)

**Comment by Natali-Oliinyk-qa** [comment]
**The link to the blog https://blog.dedicated.com/ is not hidden**
