### ISSUE TITLE
Solutions -> Clouds

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#115]
- [x] **these tabs are not fully adapted to the mobile version**
- [x] https://dev.dedicatted.com/solutions/clouds/amazon-aws/
- [x] https://dev.dedicatted.com/solutions/clouds/google-cloud/
- [x] https://dev.dedicatted.com/solutions/clouds/microsoft-azure/

![solution.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d903b8c1-7a56-4e07-8646-0f572b047fc3)

**Comment by Natali-Oliinyk-qa** [comment]
these bugs are not fixed in the extension for iPad Mini for the same pages :

- [ ]  https://dev.dedicatted.com/solutions/clouds/amazon-aws/
- [ ] https://dev.dedicatted.com/solutions/clouds/google-cloud/
- [ ]  https://dev.dedicatted.com/solutions/clouds/microsoft-azure/
![Screenshot_6.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/822da178-b251-4afe-b7fd-4d2048bedbbd)

**Comment by bcmp4p1** [comment]
about bug for ipad mini this blocks are too big for ipad display, but u can swipe it and see content
