### ISSUE TITLE
GitOps With Continuous Delivery (duplication of text in the layout) 

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#117]
- [x]        **"GitOps Continuous Delivery" tab layout contains repeating text  (desktop) **

![the same text1 _desktop.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/505b2556-a399-4a09-becb-9e150f4f63eb)
____________________________________________________________________________________________________
![the same text2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/6a827f83-1b1c-4391-b12c-b84c81dc307d)

__________________________________________________________________________________________________
- [x]        **"GitOps Continuous Delivery" tab layout contains repeating text  (mobile) **

![GitOps With Continuous Delivery(the same text).png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d2884124-2a47-46e9-8f43-4ab05b9f25e7)

**Comment by ghostring31** [comment]
2nd topic should be

Reproducible Rollbacks
Achieve stable and reproducible rollbacks, thus increasing time to recovery as well.

**Comment by bcmp4p1** [comment]
didnt fix 2nd screen, need text
