### ISSUE TITLE
infrastructure-as-a-code

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#137]
- [x]   **the same text on the layout** (is this a designer error?)
![thev sametext on the layout.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/3e35328e-bd8d-498c-97bd-148f3248d067)

**Comment by ghostring31** [comment]
Platform-agnostic

IaC tools with incredible flexibility, support the most prominent cloud platforms. Also offers community-supported providers for a wide variety of platforms.
