### ISSUE TITLE
Amazon AWS

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#147]
- [ ] after clicking "See less", the user must return to the Amazon AWS form (see more)

![less text.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/0ffeed8b-b8f6-4fea-849f-d214cb83dc77)

### **the same problem on these pages :**
- Google Cloud
- Microsoft Azure
- Kubernetes
- DevOps-As-A-Service
- Cloud migration consulting
- cloud infrastructure and designe

**Comment by KostiaLevchenko** [comment]
duplicate of issee#143
