### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#149]
AC:
- [x] Add 404 Page.
https://www.figma.com/file/an1FEcVX3sT91stDzJo6q2/April-Dedicated?node-id=1%3A5331

https://docs.google.com/spreadsheets/d/1IHdofn6cRk7USnV7e1OoydnGd7a3JsMz/edit#gid=240909817

**Comment by KostiaLevchenko** [comment]
- [x] Change to 404
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/96a5ede9-7094-42d3-9348-4c09ef29d78b)

- [x] Connect to 404 status code (discuss with @MishchenkoDaniil )
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/3fefa429-56ec-41f8-8c99-656d6a058a17)

**Comment by Natali-Oliinyk-qa** [comment]
expansion 1120-1023
![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/8f998465-a659-4db3-9827-078033635ece)
