### ISSUE TITLE
devops-as-a-service (page switches to the anchor back)

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#160]
- [x]  **page switches to the anchor back when user tries to open and select another site page in the heade**r

user on  https://dedicatted.com/what-we-do/devops/devops-as-a-service#service-level-agreement

- scroll slowly up to the header
- try to open and select another site page in the header
 - page switches to the anchor back
![prod (2).gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b35d084f-08da-45f2-bb5e-5eb90ef212a3)

**Comment by bcmp4p1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DedicattedSite-62a3051b86834e0011048147/issues/dedicatted/DedicattedZen/160?planning-poker) with Zenhub @bcmp4p1 @aleksandra-mileant
