### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#161]
#########################################################################################
Designs: https://www.figma.com/file/8uiImTkMRd0dw0p8oRn4Gk/%2F-edit-%2F-4.0.-October-%2F-all-pages-%2F?node-id=152%3A3810
#########################################################################################

AC:
- [ ] Add desktop **Home Page** page.
- [ ] Add mobile **Home Page** page.

**Comment by bcmp4p1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DedicattedSite-62a3051b86834e0011048147/issues/dedicatted/DedicattedZen/161?planning-poker) with Zenhub @bcmp4p1 @aleksandra-mileant

**Comment by Natali-Oliinyk-qa** [comment]
- [x] **The same texts on the layout**

![same text.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/2cec3115-9650-4cd6-a7bf-3a0a4282a5b4)
_____________________________________________________________________

- [x]  MOBILE  "Meet the DevOps team" form does not appear after clicking "Get for free" button
 ### 
**ACTUAL RES**
![chrome_bk6ifHlyzS.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b2ccfae0-7195-4d40-b0e5-da58dd4e9b34)

**EXPECTED RES**
![get for free.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/474c649d-43dc-4b6f-b4f4-5a4d1cb73601)

____________________________________________________________

-[ ]  **MOBILE the text placement does not match the layout**

- ACTUAL
![actual 2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/1047545f-46b5-4709-a1e6-fc648f92033c)

- EXPECTED
![expected2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/f1ebe18a-f861-4fc7-89b2-07c810165f8f)
_______________________________________________________________________
- ACTUAL

![shadow1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/2533c318-ecb0-4d98-99f6-8090dcd81b29)


- EXPECTED
![expected.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/a38dc4d1-bf74-49d5-afec-5af50cc28713)

-[ ]  **MOBILE the text placement does not match the layout**

- ACTUAL 
![expected3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b8216cbd-fb8b-41ae-8204-9e4df08c9d69)
 - EXPECTED
![actual 3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/10acd6fe-41c4-4bae-b478-341b0842769d) 


- [ ] color of the icons does not match the layout
 
- ACTUAL
![actual 4.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/3d632118-44a3-435a-aded-dc8d522e2850)

- EXPECTED
![expected4.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/37d64137-0771-4e7a-8df2-170cfc9387d3)

____________________________________________________________________
