### ISSUE TITLE
Microsoft Azure Page

### ISSUE THREAD

**Issue by aleksandra-mileant** [dedicatted/DedicattedZen#85]
- [x] Add desktop versions of page.
- [x] Add mobile versions of page.
- [x] Fix Header bug
https://www.figma.com/file/tPLEjRTOoyaCXPqqtDajwX/%2F-edit-%2F-3.0.-September-%2F-4-pages-%2F-(Copy)?node-id=1%3A11316

**Comment by aleksandra-mileant** [comment]
Having made a mobile version of the component, I noticed that the desktop one is missing.

**Comment by KostiaLevchenko** [comment]
@aleksandra-mileant 
- [x] Add contact form.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/9f26a2cd-e231-4789-a599-5d5483f193d6)

- [x] Fix the mobile version of the scroller.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/a506a36c-6e6b-4f94-8507-81edece61802)

**Comment by KostiaLevchenko** [comment]
@aleksandra-mileant 
- [x] Add header redirect to page.
