### ISSUE TITLE
Cloud Native Development

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#90]
AC:

- [x] Fix animation:
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/0d6797b0-9ce8-4fe9-9c4d-3eb661f5b199)
*example of how it should work:* https://www.figma.com/proto/hUPSawTpZuHbraBnRm62Dh/DEDICATTED-2.0---AUGUST?node-id=46%3A22232&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=46%3A22232
- [x] Add image: 
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/72e45310-67ee-4519-b1d0-65f0e667b983)

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [x] Fix background image.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/855ffb1f-0f9e-48c8-8345-f46c7b374047)

- [x] Check all fonts and text sizes.

**Comment by ArtemKardanov** [comment]
6h

**Comment by ArtemKardanov** [comment]
6h

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [ ] Fix eslint error https://github.com/dedicatted/dedicatted-com/actions/runs/3284849244/jobs/5411284993

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 

- [x] Fix animation
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/ce8ddb6c-a686-4001-bf3d-d5d510a24cd8)

- [x] Cut background object 
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/94ae6145-23dd-4e4e-9ca9-fdc5ea20c693)

**Comment by ArtemKardanov** [comment]
+ 0.5h
