### ISSUE TITLE
Cloud Cost Optimisation Page bugs

### ISSUE THREAD

**Issue by aleksandra-mileant** [dedicatted/DedicattedZen#91]
AC:
- [x] Fix "How we can  optimise cloud costs?" animation component.
https://www.figma.com/file/4hCSzr3fHoAkOLnhVsOrdv/(EDIT)-DEDICATTED-2.0---AUGUST-(EDIT)?node-id=98%3A9228
https://www.figma.com/file/4hCSzr3fHoAkOLnhVsOrdv/(EDIT)-DEDICATTED-2.0---AUGUST-(EDIT)?node-id=618%3A10971
- [x] Change the image (when you download it in svg format on the prod, for some reason it turns into a pirate)
![image.png](https://images.zenhubusercontent.com/627016a3081722e730e67681/9f1692e5-4ed7-4dee-a8dc-7ebd82c89e0c)
![image.png](https://images.zenhubusercontent.com/627016a3081722e730e67681/6decda46-d06d-4ea7-a1ce-7d1fa38773d9)
- [x] missing background image
![image.png](https://images.zenhubusercontent.com/627016a3081722e730e67681/b2cdf21f-fee6-447f-93a9-dfcb78c45634)
![image.png](https://images.zenhubusercontent.com/627016a3081722e730e67681/c596fba0-42bd-41fd-9b31-6cbf84f47e6c)

**Comment by ArtemKardanov** [comment]
10h

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 

- [x] Fix background image
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/1b422b88-55d5-4207-83b0-d7ee75dcc51f)

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [x]  Fix background image
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/cf6ea179-4983-40e2-9239-720e305c1267)

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [x]  Fix background image
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/30897508-9ff1-40d4-9e44-80c0b875d5d9)

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [x] Add image to footer form.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/1693b653-151d-4321-abf5-3d202530b79c)

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [x] Use light green instead of white for the pop-up messages outline.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/8279c4b2-bf9c-4de1-85c5-853a9b2119f7)

**Comment by KostiaLevchenko** [comment]
@ArtemKardanov 
- [x] Fix form text color
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/6f9d3faf-bb9e-451b-8438-67d7b1cb4dfa)

**Comment by ArtemKardanov** [comment]
+1h

**Comment by ArtemKardanov** [comment]
+4h
