### ISSUE TITLE
Hybrid cloud

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#94]
##########################################################################################
**Note:** Check all fonts and text sizes. 
Designs: https://www.figma.com/file/4hCSzr3fHoAkOLnhVsOrdv/(EDIT)-DEDICATTED-2.0---AUGUST-(EDIT)?node-id=21%3A27027
##########################################################################################
AC:

- [x] Fix the background image.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/03cdbf41-8c10-480e-82ef-cf0b49a857db)
_________________________________________________________________________________________________

- [x] Fix the background image.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/996cf580-cecc-42e1-b49c-66cc0c7dee27)
_________________________________________________________________________________________________

- [x] Fix designs (background image + button design)
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/be64b584-4e9a-43f7-aa1b-b3b4fdb4b120)
_________________________________________________________________________________________________

- [x] Add form call on button click.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/1c6ecdb0-1d74-43aa-985b-bac702ab309f)
_________________________________________________________________________________________________

- [x] Fix the background image.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/e74ed649-d000-4681-92e2-68b975149454)
_________________________________________________________________________________________________

- [x] Increase animation interaction zone (discuss with @KostiaLevchenko )
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/08f971b1-17ab-4ae2-b1f6-535aab6ffde5)
_________________________________________________________________________________________________

- [x] Fix designs.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/2ae5b942-c6b1-459d-9677-47884a1d693b)
_________________________________________________________________________________________________

- [x] Hide block.
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/05d4620f-ac8f-4e17-a746-13993d563c2b)

**Comment by ArtemKardanov** [comment]
2.5h

**Comment by ArtemKardanov** [comment]
+1h
