### ISSUE TITLE
 Infrastructure as a Code Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#95]
#########################################################################################
Designs: https://www.figma.com/file/8uiImTkMRd0dw0p8oRn4Gk/%2F-edit-%2F-3.0.-September-%2F-all-pages-%2F?node-id=13%3A4110
#########################################################################################

AC:
- [x] Add desktop **Infrastructure as a Code** page.
- [x] Add mobile **Infrastructure as a Code** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x]      **in the block "_Why should you use Infrastructure as a Code?_" is the text that is missing from the layout**

###  **EXPECTED RESULT**
### 
- ### **Desktop**

![text are missing in layout.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/5f30876f-8d14-4a97-b855-90d158ce30a4)

- ### **MOb**
![extra text layout (mob).png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/39fd6767-bfc6-4d95-b0f3-b3b460141684)


### **ACTUAL RESULT**

- ### **DEsktop**
![less_text.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ad29b675-b4ea-46da-b977-46eb37a59be0)

- ### **Mob**
![text is missing in layout(mob).png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e3f61c43-4e82-47ca-ac9c-560e58515f37)
___________________________________________________________________________________________________________

- [x] **elements are superimposed on the text**

![element superimprosde on text(mob).png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/c8840618-3ba6-4620-aa3e-4e1c6e294d9c)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] **the picture overlaps the text**

![overlaps the text(mob).png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/8412a60f-a6f7-43d1-9219-68c48de54c4e)
