### ISSUE TITLE
Continuous integration and delivery Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [dedicatted/DedicattedZen#97]
#########################################################################################
Designs: https://www.figma.com/file/8uiImTkMRd0dw0p8oRn4Gk/%2F-edit-%2F-3.0.-September-%2F-all-pages-%2F?node-id=13%3A17893
#########################################################################################

AC:
- [x] Add desktop **Continuous integration and delivery** page.
- [x] Add mobile **Continuous integration and delivery** page.

**Comment by ArtemKardanov** [comment]
21h
